import type { MapManifest, MapFamily } from "@atlas/data-models";

export interface MapTemplate {
  id: string;
  title: string;
  description: string;
  family: MapFamily;
  manifest: MapManifest;
}

export const TEMPLATES: MapTemplate[] = [
  {
    id: "earthquakes-live",
    title: "Jordskalv — senaste dygnet",
    description: "Realtidsdata från USGS, uppdateras var 5:e minut",
    family: "point",
    manifest: {
      id: "earthquakes-live",
      title: "Jordskalv — senaste dygnet",
      description: "Realtidsdata från USGS (M2.5+)",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 0],
      defaultZoom: 2,
      basemap: { style: "dark" },
      layers: [
        {
          id: "quakes",
          kind: "event",
          label: "Jordskalv",
          sourceType: "api",
          sourceUrl: "/api/earthquakes",
          refreshIntervalMs: 300_000,
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "point",
            colorField: "mag",
            sizeField: "mag",
            color: { scheme: "magma" },
            classification: { method: "quantile", classes: 5 },
            fillOpacity: 0.8,
          },
          legend: { title: "Magnitud", type: "gradient" },
          interaction: {
            tooltipFields: ["title", "mag", "place"],
            hoverEffect: "enlarge",
          },
          attribution: "USGS Earthquake Hazards Program",
          attributionUrl: "https://earthquake.usgs.gov",
        },
      ],
    },
  },
  {
    id: "earthquakes-heat",
    title: "Jordskalv — värmevy",
    description: "Heatmap av seismisk aktivitet senaste dygnet",
    family: "heatmap",
    manifest: {
      id: "earthquakes-heat",
      title: "Jordskalv — värmevy",
      description: "Heatmap av seismisk aktivitet (M2.5+)",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 0],
      defaultZoom: 2,
      basemap: { style: "dark" },
      layers: [
        {
          id: "quakes-heat",
          kind: "event",
          label: "Seismisk aktivitet",
          sourceType: "api",
          sourceUrl: "/api/earthquakes",
          refreshIntervalMs: 300_000,
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "heatmap",
            colorField: "mag",
            color: { scheme: "magma" },
            fillOpacity: 0.7,
          },
          legend: { title: "Seismisk intensitet", type: "gradient" },
          attribution: "USGS Earthquake Hazards Program",
          attributionUrl: "https://earthquake.usgs.gov",
        },
      ],
    },
  },
  {
    id: "europe-density",
    title: "Europa — befolkningstäthet",
    description: "Choropleth-karta med invånare per km²",
    family: "choropleth",
    manifest: {
      id: "europe-density",
      title: "Europa — befolkningstäthet",
      description: "Invånare per km² i europeiska länder",
      theme: "editorial",
      version: 2,
      defaultCenter: [54, 15],
      defaultZoom: 3.5,
      basemap: { style: "dark" },
      layers: [
        {
          id: "density",
          kind: "zone",
          label: "Befolkningstäthet",
          sourceType: "geojson-url",
          sourceUrl: "/templates/european-countries.geojson",
          geometryType: "polygon",
          style: {
            markerShape: "circle",
            mapFamily: "choropleth",
            colorField: "density",
            color: { scheme: "blues" },
            classification: { method: "quantile", classes: 5 },
            fillOpacity: 0.75,
            strokeColor: "rgba(255,255,255,0.2)",
            strokeWidth: 1,
            labelField: "name",
          },
          legend: { title: "Inv./km²", type: "gradient" },
          interaction: {
            tooltipFields: ["name", "population", "density"],
            hoverEffect: "highlight",
          },
        },
      ],
    },
  },
  {
    id: "europe-capitals",
    title: "Europas huvudstäder",
    description: "Proportionella symboler efter befolkningsstorlek",
    family: "proportional-symbol",
    manifest: {
      id: "europe-capitals",
      title: "Europas huvudstäder",
      description: "Befolkning i europeiska huvudstäder",
      theme: "editorial",
      version: 2,
      defaultCenter: [54, 15],
      defaultZoom: 3.5,
      basemap: { style: "dark" },
      layers: [
        {
          id: "capitals",
          kind: "asset",
          label: "Huvudstäder",
          sourceType: "geojson-url",
          sourceUrl: "/templates/european-capitals.geojson",
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "proportional-symbol",
            colorField: "region",
            sizeField: "population",
            color: { scheme: "set2" },
            classification: { method: "categorical", classes: 4 },
            fillOpacity: 0.8,
            strokeColor: "rgba(255,255,255,0.3)",
            strokeWidth: 1,
            labelField: "name",
          },
          legend: { title: "Befolkning", type: "proportional", exampleValues: [500_000, 2_000_000, 5_000_000] },
          interaction: {
            tooltipFields: ["name", "country", "population"],
            hoverEffect: "enlarge",
          },
        },
      ],
    },
  },
  {
    id: "europe-trade",
    title: "Handelsflöden i Europa",
    description: "Flödeskarta med handelsvolymer mellan länder",
    family: "flow",
    manifest: {
      id: "europe-trade",
      title: "Handelsflöden i Europa",
      description: "Handelsvolymer mellan europeiska länder",
      theme: "editorial",
      version: 2,
      defaultCenter: [50, 10],
      defaultZoom: 3.8,
      basemap: { style: "dark" },
      layers: [
        {
          id: "trade",
          kind: "event",
          label: "Handelsflöden",
          sourceType: "geojson-url",
          sourceUrl: "/templates/european-trade.geojson",
          geometryType: "line",
          style: {
            markerShape: "circle",
            mapFamily: "flow",
            colorField: "category",
            color: { scheme: "set2" },
            classification: { method: "categorical", classes: 3 },
            fillOpacity: 0.7,
          },
          flow: {
            originField: "origin",
            destinationField: "destination",
            weightField: "volume",
            arc: true,
            minWidth: 1,
            maxWidth: 6,
          },
          legend: { title: "Handelsvolym", type: "flow" },
          interaction: {
            tooltipFields: ["origin", "destination", "volume", "category"],
            hoverEffect: "highlight",
          },
        },
      ],
    },
  },
  {
    id: "world-gdp",
    title: "World GDP by country",
    description: "Choropleth of gross domestic product across all countries",
    family: "choropleth",
    manifest: {
      id: "world-gdp",
      title: "World GDP by country",
      description: "GDP (millions USD) from Natural Earth dataset",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 20],
      defaultZoom: 1.8,
      basemap: { style: "dark" },
      layers: [
        {
          id: "gdp",
          kind: "zone",
          label: "GDP",
          sourceType: "api",
          sourceUrl: "/api/geo/world-countries",
          geometryType: "polygon",
          style: {
            markerShape: "circle",
            mapFamily: "choropleth",
            colorField: "gdp_md",
            color: { scheme: "viridis" },
            classification: { method: "quantile", classes: 6 },
            fillOpacity: 0.8,
            strokeColor: "rgba(255,255,255,0.12)",
            strokeWidth: 0.5,
            labelField: "name",
          },
          legend: { title: "GDP (M USD)", type: "gradient" },
          interaction: {
            tooltipFields: ["name", "gdp_md", "pop_est", "continent"],
            hoverEffect: "highlight",
          },
        },
      ],
    },
  },
  {
    id: "world-population-3d",
    title: "Population — 3D",
    description: "Country populations as 3D extruded bars",
    family: "extrusion",
    manifest: {
      id: "world-population-3d",
      title: "Population — 3D",
      description: "Country population as extruded columns",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 20],
      defaultZoom: 1.8,
      basemap: { style: "dark" },
      layers: [
        {
          id: "pop-3d",
          kind: "zone",
          label: "Population",
          sourceType: "api",
          sourceUrl: "/api/geo/world-countries",
          geometryType: "polygon",
          style: {
            markerShape: "circle",
            mapFamily: "extrusion",
            colorField: "pop_est",
            color: { scheme: "plasma" },
            classification: { method: "quantile", classes: 6 },
            fillOpacity: 0.85,
          },
          extrusion: {
            heightField: "pop_est",
            minHeight: 1000,
            maxHeight: 800_000,
          },
          legend: { title: "Population", type: "gradient" },
          interaction: {
            tooltipFields: ["name", "pop_est", "continent"],
            hoverEffect: "highlight",
          },
        },
      ],
    },
  },
  {
    id: "world-cities",
    title: "World's largest cities",
    description: "Proportional symbols showing city populations worldwide",
    family: "proportional-symbol",
    manifest: {
      id: "world-cities",
      title: "World's largest cities",
      description: "Major cities by population (Natural Earth dataset)",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 20],
      defaultZoom: 1.8,
      basemap: { style: "dark" },
      layers: [
        {
          id: "cities",
          kind: "asset",
          label: "Cities",
          sourceType: "api",
          sourceUrl: "/api/geo/world-cities",
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "proportional-symbol",
            sizeField: "pop_max",
            colorField: "pop_max",
            color: { scheme: "oranges" },
            classification: { method: "quantile", classes: 5 },
            fillOpacity: 0.7,
            strokeColor: "rgba(255,255,255,0.25)",
            strokeWidth: 0.5,
            labelField: "name",
          },
          legend: { title: "Population", type: "proportional", exampleValues: [1_000_000, 5_000_000, 15_000_000] },
          interaction: {
            tooltipFields: ["name", "country", "pop_max"],
            hoverEffect: "enlarge",
          },
        },
      ],
    },
  },
  {
    id: "volcanoes-global",
    title: "Active volcanoes",
    description: "Major volcanoes around the world, clustered by region",
    family: "cluster",
    manifest: {
      id: "volcanoes-global",
      title: "Active volcanoes",
      description: "30 major active volcanoes worldwide",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 10],
      defaultZoom: 2,
      basemap: { style: "dark" },
      layers: [
        {
          id: "volcanoes",
          kind: "asset",
          label: "Volcanoes",
          sourceType: "api",
          sourceUrl: "/api/volcanoes",
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "cluster",
            colorField: "elevation",
            color: { scheme: "inferno" },
            classification: { method: "quantile", classes: 4 },
            fillOpacity: 0.85,
          },
          legend: { title: "Elevation (m)", type: "gradient" },
          interaction: {
            tooltipFields: ["name", "elevation", "country", "type"],
            hoverEffect: "enlarge",
          },
        },
      ],
    },
  },
  {
    id: "heritage-sites",
    title: "UNESCO World Heritage",
    description: "Cultural and natural heritage sites across the globe",
    family: "point",
    manifest: {
      id: "heritage-sites",
      title: "UNESCO World Heritage",
      description: "1 200+ heritage sites from the UNESCO register",
      theme: "editorial",
      version: 2,
      defaultCenter: [20, 25],
      defaultZoom: 2,
      basemap: { style: "dark" },
      layers: [
        {
          id: "heritage",
          kind: "asset",
          label: "Heritage sites",
          sourceType: "api",
          sourceUrl: "/api/heritage",
          geometryType: "point",
          style: {
            markerShape: "circle",
            mapFamily: "point",
            colorField: "category",
            color: { scheme: "set2" },
            classification: { method: "categorical", classes: 3 },
            fillOpacity: 0.8,
            strokeColor: "rgba(255,255,255,0.2)",
            strokeWidth: 0.5,
          },
          legend: { title: "Category", type: "categorical" },
          interaction: {
            tooltipFields: ["name", "category", "country", "year_inscribed"],
            hoverEffect: "enlarge",
          },
        },
      ],
    },
  },
];

export function getTemplate(id: string): MapTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
