/**
 * Global registry of official statistics APIs from national statistical agencies
 * and international organizations.
 *
 * Used by the official stats resolver to locate authoritative statistical
 * datasets and enrich web search queries with known source context.
 *
 * 72 sources across 6 continents + international organizations.
 * Verified against official documentation as of 2025-06.
 */

export type OfficialStatsApiType =
  | "pxweb"
  | "sdmx"
  | "odata"
  | "rest"
  | "ckan"
  | "portal"
  | "unknown";

export type VerificationStatus = "verified" | "provisional" | "needs_review";

export type AccessLevel =
  | "official_api"
  | "official_portal"
  | "official_data_service";

export type AuthType = "none" | "api_key" | "oauth" | "unknown";

export interface CanaryQuery {
  /** A known-good table/indicator ID for this source. */
  table: string;
  /** A search term that should return results. */
  query: string;
}

export interface OfficialStatsSource {
  id: string;
  countryCode: string | null;
  countryName: string;
  agencyName: string;
  baseUrl: string;
  docsUrl?: string;
  apiType: OfficialStatsApiType;
  accessLevel: AccessLevel;
  auth: AuthType;
  formats: string[];
  languages?: string[];
  coverageTags: string[];
  geographyLevels?: string[];
  verificationStatus: VerificationStatus;
  notes?: string;
  priority: number;
  /** Known-good query for verification. Used by canary runner to detect API drift. */
  canaryQuery?: CanaryQuery;
}

export const OFFICIAL_STATS_REGISTRY: OfficialStatsSource[] = [
  // ===== Nordic Countries =====
  {
    id: "se-scb",
    countryCode: "SE",
    countryName: "Sweden",
    agencyName: "Statistics Sweden (SCB)",
    baseUrl: "https://api.scb.se/OV0104/v2beta/api/v2",
    docsUrl: "https://www.scb.se/en/services/open-data-api/pxwebapi/pxwebapi-2.0",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv"],
    languages: ["sv", "en"],
    coverageTags: ["population", "economy", "labor", "health", "education", "housing", "environment", "energy", "transport", "agriculture", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 100,
    notes: "PxWebApi 2 / official open statistics API.",
    canaryQuery: { table: "TAB638", query: "population municipality" },
  },
  {
    id: "se-bra",
    countryCode: "SE",
    countryName: "Sweden",
    agencyName: "Swedish National Council for Crime Prevention (BRÅ)",
    baseUrl: "https://bra.se/statistik",
    docsUrl: "https://bra.se/statistik/kriminalstatistik.html",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv", "xlsx"],
    languages: ["sv", "en"],
    coverageTags: ["crime", "justice"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 80,
    notes: "Crime statistics by municipality and region. No API — data downloadable from portal.",
  },
  {
    id: "se-kolada",
    countryCode: "SE",
    countryName: "Sweden",
    agencyName: "Kolada (Municipality & Region Database)",
    baseUrl: "https://www.kolada.se/verktyg/fri-sokning/",
    docsUrl: "https://www.kolada.se/verktyg/fri-sokning/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["sv"],
    coverageTags: ["economy", "education", "health", "social", "environment", "labor"],
    geographyLevels: ["municipality", "region"],
    verificationStatus: "verified",
    priority: 85,
    notes: "Aggregated municipal key metrics. REST API at api.kolada.se.",
  },
  {
    id: "no-ssb",
    countryCode: "NO",
    countryName: "Norway",
    agencyName: "Statistics Norway (SSB)",
    baseUrl: "https://data.ssb.no/api/pxwebapi/v2",
    docsUrl: "https://www.ssb.no/en/api/pxwebapi",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv"],
    languages: ["no", "en"],
    coverageTags: ["population", "economy", "labor", "regions", "housing", "immigration", "education", "health", "social", "environment"],
    geographyLevels: ["country", "county", "municipality"],
    verificationStatus: "verified",
    priority: 100,
    canaryQuery: { table: "07459", query: "population municipality" },
  },
  {
    id: "dk-dst",
    countryCode: "DK",
    countryName: "Denmark",
    agencyName: "Statistics Denmark / StatBank",
    baseUrl: "https://api.statbank.dk/v1",
    docsUrl: "https://www.dst.dk/en/Statistik/hjaelp-til-statistikbanken/api",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv", "xml"],
    languages: ["da", "en"],
    coverageTags: ["population", "economy", "labor", "trade", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 100,
    canaryQuery: { table: "FOLK1A", query: "population" },
  },
  {
    id: "fi-stat",
    countryCode: "FI",
    countryName: "Finland",
    agencyName: "Statistics Finland",
    baseUrl: "https://pxdata.stat.fi/PXWeb/api/v1/en/StatFin",
    docsUrl: "https://stat.fi/en/services/statistical-data-services/open-data-and-interfaces/interface-use-of-databases",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv", "px"],
    languages: ["fi", "sv", "en"],
    coverageTags: ["population", "economy", "labor", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 100,
    canaryQuery: { table: "11ra", query: "population municipality" },
  },
  {
    id: "is-statice",
    countryCode: "IS",
    countryName: "Iceland",
    agencyName: "Statistics Iceland",
    baseUrl: "https://px.hagstofa.is/pxen/api/v1/en/Ibuar",
    docsUrl: "https://px.hagstofa.is/pxen/",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv", "px"],
    languages: ["is", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 92,
    canaryQuery: { table: "MAN01000", query: "population" },
    notes: "PxWeb v1 API. Verified 2026-03-29: table list returns JSON.",
  },

  // ===== European Union & UK =====
  {
    id: "eu-eurostat",
    countryCode: null,
    countryName: "European Union",
    agencyName: "Eurostat",
    baseUrl: "https://ec.europa.eu/eurostat/api/dissemination",
    docsUrl: "https://ec.europa.eu/eurostat/web/user-guides/data-browser/api-data-access/api-getting-started",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "sdmx-json", "sdmx-xml", "tsv", "csv"],
    languages: ["en", "de", "fr"],
    coverageTags: ["economy", "population", "labor", "trade", "regions", "sdg"],
    geographyLevels: ["eu", "country", "region"],
    verificationStatus: "verified",
    priority: 99,
    canaryQuery: { table: "demo_pjan", query: "population" },
  },
  {
    id: "gb-ons",
    countryCode: "GB",
    countryName: "United Kingdom",
    agencyName: "Office for National Statistics (ONS)",
    baseUrl: "https://api.beta.ons.gov.uk/v1",
    docsUrl: "https://developer.ons.gov.uk/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "local_authority"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "nl-cbs",
    countryCode: "NL",
    countryName: "Netherlands",
    agencyName: "CBS StatLine",
    baseUrl: "https://opendata.cbs.nl/ODataApi",
    docsUrl: "https://opendata.cbs.nl/statline/",
    apiType: "odata",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "odata", "xml"],
    languages: ["nl", "en"],
    coverageTags: ["population", "economy", "labor", "trade", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "ie-cso",
    countryCode: "IE",
    countryName: "Ireland",
    agencyName: "Central Statistics Office (CSO)",
    baseUrl: "https://ws.cso.ie/public/api.restful",
    docsUrl: "https://data.cso.ie/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "xml", "csv"],
    languages: ["en", "ga"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "county"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "es-ine",
    countryCode: "ES",
    countryName: "Spain",
    agencyName: "INE Spain",
    baseUrl: "https://servicios.ine.es/wstempus/js/",
    docsUrl: "https://www.ine.es/dyngs/DAB/en/index.htm?cid=1102",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "xml"],
    languages: ["es", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "province", "municipality"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "it-istat",
    countryCode: "IT",
    countryName: "Italy",
    agencyName: "ISTAT",
    baseUrl: "https://sdmx.istat.it/SDMXWS/rest/",
    docsUrl: "https://www.istat.it/en/classifications-and-tools/sdmx-web-services/",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["it", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "region", "province", "municipality"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "de-destatis",
    countryCode: "DE",
    countryName: "Germany",
    agencyName: "Destatis / GENESIS-Online",
    baseUrl: "https://www-genesis.destatis.de/genesisWS/rest/2020",
    docsUrl: "https://www.destatis.de/EN/Service/OpenData/api-webservice.html",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["json", "csv", "xml"],
    languages: ["de", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "state", "district", "municipality"],
    verificationStatus: "verified",
    priority: 94,
    notes: "Official web service; auth may apply depending on use.",
  },
  {
    id: "fr-insee",
    countryCode: "FR",
    countryName: "France",
    agencyName: "INSEE",
    baseUrl: "https://api.insee.fr/series/BDM/V1",
    docsUrl: "https://www.insee.fr/en/metadonnees/source/indicateur/p1631/bases-donnees-ligne",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "oauth",
    formats: ["json", "csv", "xml"],
    languages: ["fr", "en"],
    coverageTags: ["economy", "prices", "labor", "population"],
    geographyLevels: ["country", "region", "department", "commune"],
    verificationStatus: "verified",
    priority: 94,
    notes: "INSEE exposes several APIs; macro series API shown here.",
  },
  {
    id: "be-statbel",
    countryCode: "BE",
    countryName: "Belgium",
    agencyName: "Statbel",
    baseUrl: "https://bestat.statbel.fgov.be/bestat/api/views/",
    docsUrl: "https://statbel.fgov.be/en/statistics/bestat/faq",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["nl", "fr", "de", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "province", "municipality"],
    verificationStatus: "verified",
    priority: 93,
  },
  {
    id: "pl-stat",
    countryCode: "PL",
    countryName: "Poland",
    agencyName: "Statistics Poland (GUS)",
    baseUrl: "https://api.stat.gov.pl",
    docsUrl: "https://api.stat.gov.pl/Home/Index?lang=en",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "xml"],
    languages: ["pl", "en"],
    coverageTags: ["population", "economy", "labor", "regions"],
    geographyLevels: ["country", "voivodeship", "powiat", "gmina"],
    verificationStatus: "verified",
    priority: 93,
  },
  {
    id: "lv-csb",
    countryCode: "LV",
    countryName: "Latvia",
    agencyName: "Central Statistical Bureau of Latvia",
    baseUrl: "https://data.stat.gov.lv/api/v1/en/OSP_PUB",
    docsUrl: "https://stat.gov.lv/en/api-and-code-list-registry/api",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["xlsx", "csv", "json", "json-stat", "px"],
    languages: ["lv", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 94,
  },
  {
    id: "ch-fso",
    countryCode: "CH",
    countryName: "Switzerland",
    agencyName: "Federal Statistical Office (FSO) / STAT-TAB",
    baseUrl: "https://www.pxweb.bfs.admin.ch/api/v1/en/",
    docsUrl: "https://www.bfs.admin.ch/bfsstatic/dam/assets/orderNr%3Ado-e-00.00-PXWEB-01/master",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv", "px"],
    languages: ["de", "fr", "it", "en"],
    coverageTags: ["population", "economy", "labor", "regions"],
    geographyLevels: ["country", "canton", "district", "municipality"],
    verificationStatus: "verified",
    priority: 94,
  },
  {
    id: "pt-ine",
    countryCode: "PT",
    countryName: "Portugal",
    agencyName: "Statistics Portugal (INE)",
    baseUrl: "https://www.ine.pt/ine/json_indicador",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json"],
    languages: ["pt", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "provisional",
    priority: 90,
  },
  {
    id: "ee-stat",
    countryCode: "EE",
    countryName: "Estonia",
    agencyName: "Statistics Estonia",
    baseUrl: "https://andmed.stat.ee/api/v1/en/stat",
    docsUrl: "https://andmed.stat.ee/en/stat",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["json", "csv", "px"],
    languages: ["et", "en"],
    coverageTags: ["population", "economy", "labor", "regions"],
    geographyLevels: ["country", "county", "municipality"],
    verificationStatus: "verified",
    priority: 90,
    canaryQuery: { table: "RV0222U", query: "population" },
    notes: "PxWeb v1 API. Verified 2026-03-29: table list returns JSON (71ms).",
  },
  {
    id: "at-stat",
    countryCode: "AT",
    countryName: "Austria",
    agencyName: "Statistics Austria / STATcube",
    baseUrl: "https://www.statistik.at/en/databases/statcube-statistical-database",
    docsUrl: "https://www.statistik.at/en/databases/statcube-statistical-database/subscription-access",
    apiType: "portal",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["csv", "xlsx"],
    languages: ["de", "en"],
    coverageTags: ["population", "economy", "labor", "regions"],
    geographyLevels: ["country", "state", "district", "municipality"],
    verificationStatus: "provisional",
    priority: 88,
    notes: "Official statistical database; API/subscription oriented.",
  },
  {
    id: "si-stat",
    countryCode: "SI",
    countryName: "Slovenia",
    agencyName: "Statistical Office of Slovenia / SiStat",
    baseUrl: "https://pxweb.stat.si/SiStatData/api/v1/en/Data",
    docsUrl: "https://pxweb.stat.si/sistat/en",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["px", "csv", "xlsx", "json"],
    languages: ["sl", "en"],
    coverageTags: ["population", "economy", "labor", "environment", "regions"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 90,
    canaryQuery: { table: "0156101S", query: "temperature" },
    notes: "PxWeb v1 API. Verified 2026-03-29: table list returns JSON (287ms).",
  },
  {
    id: "cy-cystat",
    countryCode: "CY",
    countryName: "Cyprus",
    agencyName: "Statistical Service of Cyprus / CYSTAT-DB",
    baseUrl: "https://cystatdb.cystat.gov.cy/api/v1/en/8.CYSTAT-DB",
    docsUrl: "https://www.gov.cy/en/service/customised-statistical-data-tables-graphs-and-apis/",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["json", "csv", "xlsx", "px"],
    languages: ["el", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "district", "municipality"],
    verificationStatus: "verified",
    priority: 91,
  },
  {
    id: "mk-makstat",
    countryCode: "MK",
    countryName: "North Macedonia",
    agencyName: "State Statistical Office / MakStat",
    baseUrl: "https://makstat.stat.gov.mk/PXWeb/api/v1/en/MakStat",
    docsUrl: "https://www.stat.gov.mk/OtvoreniPodatociApi_en.aspx",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv", "xml", "xlsx", "px"],
    languages: ["mk", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 92,
  },
  {
    id: "rs-stat",
    countryCode: "RS",
    countryName: "Serbia",
    agencyName: "Statistical Office of the Republic of Serbia",
    baseUrl: "https://opendata.stat.gov.rs/odata/",
    docsUrl: "https://opendata.stat.gov.rs/odata/?id=en-us",
    apiType: "odata",
    accessLevel: "official_api",
    auth: "none",
    formats: ["odata", "json", "csv"],
    languages: ["sr", "en"],
    coverageTags: ["population", "economy", "labor", "sdg"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 92,
  },
  {
    id: "mt-nso",
    countryCode: "MT",
    countryName: "Malta",
    agencyName: "National Statistics Office Malta",
    baseUrl: "https://apidesign-statdb.nso.gov.mt/rest/v2/",
    docsUrl: "https://portal.data.gov.mt/en_GB/organization/3fd1c612-c3dc-494a-8dda-14ccc423758b?organization=national-statistics-office",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-xml", "csv"],
    languages: ["mt", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region"],
    verificationStatus: "verified",
    priority: 91,
  },
  {
    id: "am-armstat",
    countryCode: "AM",
    countryName: "Armenia",
    agencyName: "Statistical Committee of Armenia / ArmStatBank",
    baseUrl: "https://statbank.armstat.am/pxweb/api/v1/en/ArmStatBank",
    docsUrl: "https://statbank.armstat.am/pxweb/en/ArmStatBank/",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["px", "csv", "xlsx", "json"],
    languages: ["hy", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "environment"],
    geographyLevels: ["country", "region", "community"],
    verificationStatus: "provisional",
    priority: 89,
    notes: "Audit 2026-03-29: HTTP 500 server error. PxWeb instance may be intermittent.",
  },
  {
    id: "lt-stat",
    countryCode: "LT",
    countryName: "Lithuania",
    agencyName: "Official Statistics Portal Lithuania",
    baseUrl: "https://osp.stat.gov.lt/en",
    docsUrl: "https://osp.stat.gov.lt/en",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv", "xlsx"],
    languages: ["lt", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "county", "municipality"],
    verificationStatus: "needs_review",
    priority: 82,
    notes: "Audit 2026-03-29: HTTP 403 Forbidden. Portal may require browser session. No direct API found.",
  },
  {
    id: "jo-dos",
    countryCode: "JO",
    countryName: "Jordan",
    agencyName: "Department of Statistics / Jordan Data Portal",
    baseUrl: "https://jdp.dos.gov.jo/",
    docsUrl: "https://jdp.dos.gov.jo/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv"],
    languages: ["ar", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "governorate"],
    verificationStatus: "provisional",
    priority: 84,
    notes: "Audit 2026-03-29: Timeout after 10s. Portal unreachable.",
  },

  // ===== Americas =====
  {
    id: "us-census",
    countryCode: "US",
    countryName: "United States",
    agencyName: "U.S. Census Bureau",
    baseUrl: "https://api.census.gov/data",
    docsUrl: "https://www.census.gov/data/developers/guidance/api-user-guide.html",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["population", "economy", "housing", "business"],
    geographyLevels: ["country", "state", "county", "tract", "place"],
    verificationStatus: "verified",
    priority: 100,
    notes: "API key recommended but not required for low-volume usage.",
    canaryQuery: { table: "acs/acs5", query: "population" },
  },
  {
    id: "us-bls",
    countryCode: "US",
    countryName: "United States",
    agencyName: "Bureau of Labor Statistics (BLS)",
    baseUrl: "https://api.bls.gov/publicAPI/v2",
    docsUrl: "https://www.bls.gov/developers/home.htm",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json"],
    languages: ["en"],
    coverageTags: ["labor", "employment", "prices", "wages"],
    geographyLevels: ["country", "state", "metro"],
    verificationStatus: "verified",
    priority: 96,
    notes: "Verified 2026-03-29: POST /timeseries/data returns data. Free tier: 25 queries/day without key, 500/day with key.",
    canaryQuery: { table: "LAUCN040010000000005", query: "unemployment rate" },
  },
  {
    id: "us-bea",
    countryCode: "US",
    countryName: "United States",
    agencyName: "Bureau of Economic Analysis (BEA)",
    baseUrl: "https://apps.bea.gov/api/data",
    docsUrl: "https://apps.bea.gov/api/_pdf/bea_web_service_api_user_guide.pdf",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "xml"],
    languages: ["en"],
    coverageTags: ["economy", "trade", "prices"],
    geographyLevels: ["country", "state", "metro", "county"],
    verificationStatus: "verified",
    priority: 96,
    notes: "Verified 2026-03-29: endpoint responds (200). Free API key required for data queries.",
    canaryQuery: { table: "SAGDP1", query: "gdp state" },
  },
  {
    id: "us-fred",
    countryCode: "US",
    countryName: "United States",
    agencyName: "Federal Reserve Economic Data (FRED)",
    baseUrl: "https://api.stlouisfed.org/fred",
    docsUrl: "https://fred.stlouisfed.org/docs/api/fred/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "xml"],
    languages: ["en"],
    coverageTags: ["economy", "finance", "prices", "labor", "housing"],
    geographyLevels: ["country", "state", "metro", "county"],
    verificationStatus: "provisional",
    priority: 98,
    notes: "Audit 2026-03-29: endpoint responds (400 without key). 800k+ time series. Free API key required.",
    canaryQuery: { table: "GDP", query: "gross domestic product" },
  },
  {
    id: "us-cdc",
    countryCode: "US",
    countryName: "United States",
    agencyName: "Centers for Disease Control and Prevention (CDC)",
    baseUrl: "https://data.cdc.gov/resource",
    docsUrl: "https://dev.socrata.com/foundry/data.cdc.gov/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["health", "mortality", "disease"],
    geographyLevels: ["country", "state", "county"],
    verificationStatus: "verified",
    priority: 92,
    notes: "Verified 2026-03-29: SODA API returns JSON. No key required for low-volume.",
    canaryQuery: { table: "bi63-dtpu", query: "mortality" },
  },
  {
    id: "us-fbi-ucr",
    countryCode: "US",
    countryName: "United States",
    agencyName: "FBI Crime Data Explorer",
    baseUrl: "https://api.usa.gov/crime/fbi/cde",
    docsUrl: "https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/docApi",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json"],
    languages: ["en"],
    coverageTags: ["crime", "justice"],
    geographyLevels: ["country", "state", "agency"],
    verificationStatus: "provisional",
    priority: 90,
    notes: "Audit 2026-03-29: endpoint responds (400 format error). Uniform Crime Reporting. Free API key via api.data.gov.",
    canaryQuery: { table: "summarized/state/CA/violent-crime", query: "violent crime" },
  },
  {
    id: "ca-statcan",
    countryCode: "CA",
    countryName: "Canada",
    agencyName: "Statistics Canada",
    baseUrl: "https://www.statcan.gc.ca/en/microdata/api",
    docsUrl: "https://www.statcan.gc.ca/en/microdata/api",
    apiType: "sdmx",
    accessLevel: "official_data_service",
    auth: "none",
    formats: ["json", "sdmx-json", "sdmx-xml", "csv"],
    languages: ["en", "fr"],
    coverageTags: ["population", "economy", "labor", "trade", "prices"],
    geographyLevels: ["country", "province", "cma", "municipality"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "mx-inegi",
    countryCode: "MX",
    countryName: "Mexico",
    agencyName: "INEGI",
    baseUrl: "https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/",
    docsUrl: "https://en.www.inegi.org.mx/servicios/api_indicadores.html",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "xml"],
    languages: ["es"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "state", "municipality"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "br-ibge",
    countryCode: "BR",
    countryName: "Brazil",
    agencyName: "IBGE",
    baseUrl: "https://servicodados.ibge.gov.br/api/v1",
    docsUrl: "https://servicodados.ibge.gov.br/api/docs/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json"],
    languages: ["pt"],
    coverageTags: ["population", "economy", "geography", "prices"],
    geographyLevels: ["country", "state", "municipality"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "ar-datosgobar",
    countryCode: "AR",
    countryName: "Argentina",
    agencyName: "datos.gob.ar / official series APIs",
    baseUrl: "https://apis.datos.gob.ar/series/api/",
    docsUrl: "https://www.datos.gob.ar/apis",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["es"],
    coverageTags: ["economy", "prices", "population", "trade"],
    geographyLevels: ["country", "province"],
    verificationStatus: "verified",
    priority: 90,
  },
  {
    id: "cl-ine",
    countryCode: "CL",
    countryName: "Chile",
    agencyName: "INE Chile",
    baseUrl: "https://api.ine.cl/",
    docsUrl: "https://www.ine.gob.cl/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "unknown",
    formats: ["json"],
    languages: ["es"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "commune"],
    verificationStatus: "needs_review",
    priority: 80,
    notes: "Audit 2026-03-29: ENOTFOUND — DNS does not resolve. API URL is dead. Demoted to portal.",
  },
  {
    id: "co-dane",
    countryCode: "CO",
    countryName: "Colombia",
    agencyName: "DANE",
    baseUrl: "https://api.dane.gov.co/",
    docsUrl: "https://www.dane.gov.co/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "unknown",
    formats: ["json"],
    languages: ["es"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "department", "municipality"],
    verificationStatus: "needs_review",
    priority: 80,
    notes: "Audit 2026-03-29: ENOTFOUND — DNS does not resolve. API URL is dead. Demoted to portal.",
  },
  {
    id: "pe-inei",
    countryCode: "PE",
    countryName: "Peru",
    agencyName: "INEI",
    baseUrl: "https://api.inei.gob.pe/",
    docsUrl: "https://www.inei.gob.pe/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "unknown",
    formats: ["json"],
    languages: ["es"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "province", "district"],
    verificationStatus: "needs_review",
    priority: 80,
    notes: "Audit 2026-03-29: Timeout after 10s. API URL unreachable. Demoted to portal.",
  },

  // ===== Asia =====
  {
    id: "jp-estat",
    countryCode: "JP",
    countryName: "Japan",
    agencyName: "e-Stat / Statistics Bureau of Japan",
    baseUrl: "https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData",
    docsUrl: "https://www.e-stat.go.jp/en/developer",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json", "xml", "csv"],
    languages: ["ja", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "prefecture", "municipality"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "sg-datagovsg",
    countryCode: "SG",
    countryName: "Singapore",
    agencyName: "data.gov.sg",
    baseUrl: "https://api-open.data.gov.sg/",
    docsUrl: "https://guide.data.gov.sg/developer-guide/api-overview",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["population", "transport", "environment", "economy"],
    geographyLevels: ["country", "planning_area"],
    verificationStatus: "verified",
    priority: 88,
  },
  {
    id: "in-datagovin",
    countryCode: "IN",
    countryName: "India",
    agencyName: "data.gov.in",
    baseUrl: "https://api.data.gov.in/resource/",
    docsUrl: "https://www.data.gov.in/apis",
    apiType: "ckan",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["json", "csv", "xml"],
    languages: ["en", "hi"],
    coverageTags: ["population", "economy", "agriculture", "health", "transport"],
    geographyLevels: ["country", "state", "district"],
    verificationStatus: "verified",
    priority: 88,
  },
  {
    id: "id-bps",
    countryCode: "ID",
    countryName: "Indonesia",
    agencyName: "BPS Statistics Indonesia",
    baseUrl: "https://webapi.bps.go.id/v1/api/",
    docsUrl: "https://webapi.bps.go.id/developer",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "api_key",
    formats: ["json"],
    languages: ["id", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "province", "regency", "city"],
    verificationStatus: "verified",
    priority: 92,
  },
  {
    id: "il-cbs",
    countryCode: "IL",
    countryName: "Israel",
    agencyName: "Central Bureau of Statistics (Israel)",
    baseUrl: "https://api.cbs.gov.il/index/data",
    docsUrl: "https://www.cbs.gov.il/en/Pages/Api-interface.aspx",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "xml"],
    languages: ["he", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "district", "locality"],
    verificationStatus: "verified",
    priority: 91,
  },
  {
    id: "th-nso",
    countryCode: "TH",
    countryName: "Thailand",
    agencyName: "National Statistical Office Thailand",
    baseUrl: "https://sdmx.nso.go.th/",
    docsUrl: "https://sdmx.nso.go.th/",
    apiType: "sdmx",
    accessLevel: "official_data_service",
    auth: "unknown",
    formats: ["sdmx-xml", "sdmx-json"],
    languages: ["th", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "province"],
    verificationStatus: "provisional",
    priority: 84,
    notes: "Audit 2026-03-29: base URL responds (200 HTML) but /rest/dataflow returns 404. SDMX endpoint path unclear.",
  },
  {
    id: "kr-kostat",
    countryCode: "KR",
    countryName: "South Korea",
    agencyName: "KOSTAT",
    baseUrl: "https://kostat.go.kr/portal/eng/openapi.action",
    docsUrl: "https://kostat.go.kr/portal/eng/openapi.action",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["json", "xml"],
    languages: ["ko", "en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "province", "city"],
    verificationStatus: "provisional",
    priority: 84,
    notes: "Audit 2026-03-29: ECONNRESET — connection refused. May block non-Korean IPs.",
  },
  {
    id: "ph-psa",
    countryCode: "PH",
    countryName: "Philippines",
    agencyName: "Philippine Statistics Authority / OpenSTAT",
    baseUrl: "https://openstat.psa.gov.ph/",
    docsUrl: "https://openstat.psa.gov.ph/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv", "xlsx"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "prices", "agriculture"],
    geographyLevels: ["country", "region", "province", "municipality"],
    verificationStatus: "provisional",
    priority: 82,
    notes: "Audit 2026-03-29: HTTP 403 Forbidden. Portal blocks automated access.",
  },
  {
    id: "np-nso",
    countryCode: "NP",
    countryName: "Nepal",
    agencyName: "National Statistics Office Nepal Data Portal",
    baseUrl: "https://data.nsonepal.gov.np/",
    docsUrl: "https://data.nsonepal.gov.np/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv"],
    languages: ["en"],
    coverageTags: ["population", "economy"],
    geographyLevels: ["country", "province", "district"],
    verificationStatus: "provisional",
    priority: 80,
    notes: "Audit 2026-03-29: CERT_HAS_EXPIRED — SSL certificate expired. Portal inaccessible.",
  },

  // ===== Africa =====
  {
    id: "za-statssa",
    countryCode: "ZA",
    countryName: "South Africa",
    agencyName: "Statistics South Africa",
    baseUrl: "https://www.statssa.gov.za/",
    docsUrl: "https://www.statssa.gov.za/",
    apiType: "portal",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["csv", "xlsx"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "province", "municipality"],
    verificationStatus: "provisional",
    priority: 78,
    notes: "Official statistics portal; add direct API only after validation.",
  },
  {
    id: "gh-gss",
    countryCode: "GH",
    countryName: "Ghana",
    agencyName: "Ghana Statistical Service / StatsBank Ghana",
    baseUrl: "https://statsbank.statsghana.gov.gh/pxweb/api/v1/en/GHA",
    docsUrl: "https://statsbank.statsghana.gov.gh/pxweb/en/",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["px", "csv", "xlsx", "json"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "agriculture", "trade"],
    geographyLevels: ["country", "region", "district"],
    verificationStatus: "verified",
    priority: 90,
  },

  // ===== Nordic Territories =====
  {
    id: "gl-stat",
    countryCode: "GL",
    countryName: "Greenland",
    agencyName: "Statistics Greenland (Grønlands Statistik)",
    baseUrl: "https://bank.stat.gl/api/v1/en/Greenland",
    docsUrl: "https://bank.stat.gl/pxweb/en/Greenland/",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv", "px"],
    languages: ["kl", "da", "en"],
    coverageTags: ["population", "economy", "labor", "fisheries", "environment"],
    geographyLevels: ["country", "municipality"],
    verificationStatus: "verified",
    priority: 80,
    notes: "Verified 2026-03-29: PxWeb v1 API returns JSON table list (409ms). Danish realm autonomous territory.",
    canaryQuery: { table: "BEXBBX1", query: "population" },
  },
  {
    id: "fo-hagstova",
    countryCode: "FO",
    countryName: "Faroe Islands",
    agencyName: "Statistics Faroe Islands (Hagstova Føroya)",
    baseUrl: "https://statbank.hagstova.fo/pxweb/api/v1/en/H2",
    docsUrl: "https://statbank.hagstova.fo/pxweb/en/H2/",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv", "px"],
    languages: ["fo", "en"],
    coverageTags: ["population", "economy", "labor", "fisheries", "trade"],
    geographyLevels: ["country", "municipality"],
    verificationStatus: "provisional",
    priority: 78,
    notes: "Audit 2026-03-29: HTTP 500 — PxWeb instance may be intermittent. Danish realm autonomous territory.",
    canaryQuery: { table: "MAN01000", query: "population" },
  },

  // ===== Caucasus =====
  {
    id: "ge-geostat",
    countryCode: "GE",
    countryName: "Georgia",
    agencyName: "National Statistics Office of Georgia (Geostat)",
    baseUrl: "https://pc-axis.geostat.ge/PXWeb/api/v1/en/Database",
    docsUrl: "https://www.geostat.ge/en/modules/categories/396/open-data",
    apiType: "pxweb",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "json-stat", "csv", "px"],
    languages: ["ka", "en"],
    coverageTags: ["population", "economy", "labor", "prices", "agriculture"],
    geographyLevels: ["country", "region", "municipality"],
    verificationStatus: "verified",
    priority: 85,
    notes: "Verified 2026-03-29: PxWeb v1 API returns JSON table list (673ms). Only PxWeb-enabled Caucasian stats office.",
    canaryQuery: { table: "Demo_01", query: "population" },
  },

  // ===== Oceania =====
  {
    id: "au-abs",
    countryCode: "AU",
    countryName: "Australia",
    agencyName: "Australian Bureau of Statistics (ABS)",
    baseUrl: "https://data.api.abs.gov.au/rest/data/",
    docsUrl: "https://www.abs.gov.au/about/data-services/application-programming-interfaces-apis/data-api-user-guide",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "prices", "regions"],
    geographyLevels: ["country", "state", "sa2", "sa3", "sa4", "lga"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "nz-stats",
    countryCode: "NZ",
    countryName: "New Zealand",
    agencyName: "Stats NZ",
    baseUrl: "https://api.stats.govt.nz/",
    docsUrl: "https://portal.apis.stats.govt.nz/",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "api_key",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "prices"],
    geographyLevels: ["country", "region", "territorial_authority"],
    verificationStatus: "verified",
    priority: 90,
  },

  // ===== International Organizations =====
  {
    id: "intl-worldbank",
    countryCode: null,
    countryName: "International",
    agencyName: "World Bank",
    baseUrl: "https://api.worldbank.org",
    docsUrl: "https://datahelpdesk.worldbank.org/knowledgebase/articles/1886701-sdmx-api-queries",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv", "json"],
    languages: ["en"],
    coverageTags: ["development", "economy", "population", "poverty", "health", "education"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 98,
    canaryQuery: { table: "NY.GDP.PCAP.CD", query: "gdp per capita" },
  },
  {
    id: "intl-imf",
    countryCode: null,
    countryName: "International",
    agencyName: "IMF",
    baseUrl: "https://api.imf.org/external/sdmx/2.1/",
    docsUrl: "https://data.imf.org/en/Resource-Pages/IMF-API",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["en"],
    coverageTags: ["macroeconomy", "finance", "bop", "prices"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 98,
  },
  {
    id: "intl-oecd",
    countryCode: null,
    countryName: "International",
    agencyName: "OECD",
    baseUrl: "https://sdmx.oecd.org/public/rest/",
    docsUrl: "https://www.oecd.org/en/data/insights/data-explainers/2024/09/api.html",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["en"],
    coverageTags: ["economy", "labor", "education", "health", "trade", "regions"],
    geographyLevels: ["global", "country", "region"],
    verificationStatus: "verified",
    priority: 98,
    canaryQuery: { table: "QNA", query: "gdp quarterly" },
  },
  {
    id: "intl-unsdg",
    countryCode: null,
    countryName: "International",
    agencyName: "UN SDG API",
    baseUrl: "https://unstats.un.org/sdgapi/v1/sdg/",
    docsUrl: "https://unstats.un.org/sdgapi/swagger/",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["sdg", "development", "population", "environment", "health"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "intl-unsd",
    countryCode: null,
    countryName: "International",
    agencyName: "UN Statistics Division / UNdata API Catalogue",
    baseUrl: "https://unstats.un.org/unsd/api/",
    docsUrl: "https://unstats.un.org/unsd/api/",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "none",
    formats: ["soap", "xml", "sdmx"],
    languages: ["en"],
    coverageTags: ["general_statistics", "trade", "demography", "environment"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 92,
  },
  {
    id: "intl-who",
    countryCode: null,
    countryName: "International",
    agencyName: "WHO Global Health Observatory",
    baseUrl: "https://ghoapi.azureedge.net/api/",
    docsUrl: "https://www.who.int/data/gho/info/gho-odata-api",
    apiType: "odata",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "xml", "odata"],
    languages: ["en"],
    coverageTags: ["health", "mortality", "life_expectancy", "disease"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 96,
  },
  {
    id: "intl-fao",
    countryCode: null,
    countryName: "International",
    agencyName: "FAO / FAOSTAT",
    baseUrl: "https://fenixservices.fao.org/faostat/api/v1/en/",
    docsUrl: "https://www.fao.org/faostat/",
    apiType: "rest",
    accessLevel: "official_data_service",
    auth: "none",
    formats: ["json", "csv"],
    languages: ["en"],
    coverageTags: ["agriculture", "food", "trade", "land"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "intl-ecb",
    countryCode: null,
    countryName: "Euro Area / Europe",
    agencyName: "European Central Bank (ECB) Data Portal",
    baseUrl: "https://data-api.ecb.europa.eu/service/",
    docsUrl: "https://data.ecb.europa.eu/help/api/overview",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["en"],
    coverageTags: ["monetary", "banking", "finance", "prices"],
    geographyLevels: ["euro_area", "country"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "intl-bis",
    countryCode: null,
    countryName: "International",
    agencyName: "Bank for International Settlements (BIS)",
    baseUrl: "https://stats.bis.org/api/v2/",
    docsUrl: "https://stats.bis.org/api-doc/v2/",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["sdmx-json", "sdmx-xml", "csv"],
    languages: ["en"],
    coverageTags: ["banking", "credit", "fx", "financial"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "intl-ilostat",
    countryCode: null,
    countryName: "International",
    agencyName: "ILOSTAT",
    baseUrl: "https://rplumber.ilo.org/data/indicator/",
    docsUrl: "https://ilostat.ilo.org/resources/sdmx-tools/",
    apiType: "sdmx",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json", "csv", "sdmx-json", "sdmx-xml"],
    languages: ["en"],
    coverageTags: ["labor", "employment", "unemployment", "wages"],
    geographyLevels: ["global", "country"],
    verificationStatus: "verified",
    priority: 95,
  },
  {
    id: "intl-cepalstat",
    countryCode: null,
    countryName: "Latin America & Caribbean",
    agencyName: "CEPALSTAT / ECLAC",
    baseUrl: "https://statistics.cepal.org/portal/cepalstat/api/",
    docsUrl: "https://statistics.cepal.org/portal/cepalstat/open-data.html?lang=en",
    apiType: "rest",
    accessLevel: "official_api",
    auth: "none",
    formats: ["json"],
    languages: ["en", "es"],
    coverageTags: ["economy", "social", "gender", "environment", "trade"],
    geographyLevels: ["regional", "country"],
    verificationStatus: "verified",
    priority: 92,
  },
  {
    id: "intl-unece",
    countryCode: null,
    countryName: "Europe / Eurasia",
    agencyName: "UNECE Data Portal",
    baseUrl: "https://w3.unece.org/PXWeb/api/v1/en/Stat",
    docsUrl: "https://unece.org/data",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["px", "csv", "xlsx", "json"],
    languages: ["en"],
    coverageTags: ["population", "economy", "transport", "environment", "gender"],
    geographyLevels: ["regional", "country"],
    verificationStatus: "verified",
    priority: 90,
  },
  {
    id: "intl-nordicstats",
    countryCode: null,
    countryName: "Nordic Region",
    agencyName: "Nordic Statistics",
    baseUrl: "https://pxweb.nordicstatistics.org/pxweb/api/v1/en/Nordic%20Statistics",
    docsUrl: "https://www.nordicstatistics.org/",
    apiType: "pxweb",
    accessLevel: "official_portal",
    auth: "none",
    formats: ["px", "csv", "xlsx", "json"],
    languages: ["en"],
    coverageTags: ["population", "economy", "labor", "education", "culture"],
    geographyLevels: ["regional", "country"],
    verificationStatus: "verified",
    priority: 88,
  },
];

// Build lookup indexes for fast queries
export const sourcesByCountry = new Map<string, OfficialStatsSource[]>();
export const sourcesByApiType = new Map<OfficialStatsApiType, OfficialStatsSource[]>();
export const sourcesByCoverageTag = new Map<string, OfficialStatsSource[]>();

for (const source of OFFICIAL_STATS_REGISTRY) {
  // Index by country code
  if (source.countryCode) {
    const countryCode = source.countryCode.toUpperCase();
    if (!sourcesByCountry.has(countryCode)) {
      sourcesByCountry.set(countryCode, []);
    }
    sourcesByCountry.get(countryCode)!.push(source);
  }

  // Index by API type
  if (!sourcesByApiType.has(source.apiType)) {
    sourcesByApiType.set(source.apiType, []);
  }
  sourcesByApiType.get(source.apiType)!.push(source);

  // Index by coverage tags
  for (const tag of source.coverageTags) {
    if (!sourcesByCoverageTag.has(tag)) {
      sourcesByCoverageTag.set(tag, []);
    }
    sourcesByCoverageTag.get(tag)!.push(source);
  }
}

/**
 * Get all sources for a specific country by ISO-2 code.
 * Returns sources sorted by priority (highest first).
 */
export function getSourcesForCountry(countryCode: string): OfficialStatsSource[] {
  const sources = sourcesByCountry.get(countryCode.toUpperCase()) ?? [];
  return sources.sort((a, b) => b.priority - a.priority);
}

/**
 * Get all international sources (World Bank, IMF, OECD, UN, etc.).
 * Returns sources sorted by priority (highest first).
 */
export function getInternationalSources(): OfficialStatsSource[] {
  const sources = OFFICIAL_STATS_REGISTRY.filter((s) => s.countryCode === null);
  return sources.sort((a, b) => b.priority - a.priority);
}
